site_name: Adabox 19 Tutorial
site_url: https://example.com/
nav:
    - Home: index.md
    - Update CP: updatecp.md
    - Libraries: libraries.md
    - Troubleshooting: troubleshooting.md
    - Examples: examples.md
